// Chart data page: interface texts and the guide (what every figure means and when it matters), in Chinese and
// English. The song texts themselves come from songs.json in the language chosen on the page.

export const UI = {
  zh: {
    app: "谱面数据", views: { rank: "排行", charts: "图表", guide: "说明" },
    all: "全部", search: "搜索曲名、读音、作者…", songs: (n) => `${n} 首`, chartsN: (n) => `${n} 张谱面`,
    diff: { easy: "Easy", normal: "Normal", hard: "Hard", expert: "Expert" },
    rankBy: {
      efficiency: "效率", speed: "最快", level: "最高等级", notes: "Notes 最多", long: "最长", short: "最短", skip: "跳过得分",
    },
    speedBy: { density: "密度", bpmMax: "最高 BPM", bpm: "主 BPM" },
    rankHint: {
      efficiency: "每分钟能拿多少分（每点综合力）。按下方技能数值和每局额外耗时计算。",
      speed: "按音符密度或 BPM 排序，衡量手速需求。",
      level: "按显示等级（含小数）排序，同级按 Notes 数。",
      notes: "判定音符数，即全连所需连击数。",
      long: "按 BGM 时长排序。", short: "按 BGM 时长从短到长。",
      skip: "使用跳过时，每点综合力能得多少分；与时长无关。",
    },
    length: "时长", bgm: "BGM", chart: "谱面", overhead: "每局额外耗时", skills: "技能加成 %",
    presets: [["满级", "140,140,140,140,140"], ["全 100", "100,100,100,100,100"], ["无技能", "0,0,0,0,0"]],
    frontier: "只看前沿", col: {
      rank: "#", song: "曲目", level: "等级", time: "时长", bpm: "BPM", notes: "Notes", density: "N/s",
      rate: "分/综合力", perMinute: "分/综合力/分钟", relative: "相对", dom: "支配", skip: "跳过系数", base: "基础系数",
    },
    onFrontier: "前沿", dominatedBy: (n) => `被 ${n} 张支配`, tipDom: (s) => `任何卡组、任何额外耗时下都不如：${s}`,
    noStats: "这个站点没有 chart-stats.json，效率相关的数据不可用。",
    axes: {
      displayLevel: "等级", density: "密度 N/s", bpm: "主 BPM", bpmMax: "最高 BPM", notes: "Notes", bgmMs: "BGM 时长 (s)",
      perMinute: "分/综合力/分钟", rate: "分/综合力", base: "基础系数", skip: "跳过系数",
    },
    scatter: "散点图", x: "横轴", y: "纵轴", levelDist: "等级分布", bandShare: "各乐队曲目数",
    moenotes: "在 moenotes 查看", moenotesHint: "作词作曲、演唱、音频、封面和谱面预览见 moenotes 歌曲页",
    detail: {
      musicType: "曲种", bgm: "BGM", musicId: "歌曲 ID", scoreId: "谱面 ID",
      notes: "Notes", fullCombo: "全连数", density: "密度", bpm: "BPM", bpmChanges: (n) => `${n} 次变速`,
      span: "音符区间", musicLength: "谱面长度", timeline: "时间轴", fever: "Fever", skill: "技能",
      composition: "音符构成", weights: "技能位权重", weightsHint: "每 +100% 技能在该位置带来的分数（每点综合力）。把最强的技能放在最高的位置。",
      efficiency: "效率（当前设置）", close: "关闭",
    },
    kinds: { tap: "点击", flick: "划键", slide: "长条", trace: "追踪", combo: "连击节点" },
    loading: "读取中…", error: "错误", source: (r, v) => `数据：${r} 区服 · master ${v}`,
  },
  en: {
    app: "Chart data", views: { rank: "Rankings", charts: "Charts", guide: "Guide" },
    all: "All", search: "Search title, reading, credits…", songs: (n) => `${n} songs`, chartsN: (n) => `${n} charts`,
    diff: { easy: "Easy", normal: "Normal", hard: "Hard", expert: "Expert" },
    rankBy: {
      efficiency: "Efficiency", speed: "Fastest", level: "Highest level", notes: "Most notes", long: "Longest",
      short: "Shortest", skip: "Skip score",
    },
    speedBy: { density: "Density", bpmMax: "Max BPM", bpm: "Main BPM" },
    rankHint: {
      efficiency: "Score per minute of play per point of power, for the skill values and overhead below.",
      speed: "By note density or BPM: how fast the chart asks you to play.",
      level: "By display level (with decimals), then by notes.",
      notes: "Judged notes, the combo of a full combo.",
      long: "By BGM length.", short: "By BGM length, shortest first.",
      skip: "Score per point of power of a skipped live; the length does not matter.",
    },
    length: "Length", bgm: "BGM", chart: "Chart", overhead: "Overhead per play", skills: "Skill score up %",
    presets: [["Max", "140,140,140,140,140"], ["All 100", "100,100,100,100,100"], ["None", "0,0,0,0,0"]],
    frontier: "Frontier only", col: {
      rank: "#", song: "Song", level: "Level", time: "Time", bpm: "BPM", notes: "Notes", density: "N/s",
      rate: "Score/power", perMinute: "Score/power/min", relative: "Rel.", dom: "Beaten", skip: "Skip", base: "Base",
    },
    onFrontier: "frontier", dominatedBy: (n) => `by ${n}`, tipDom: (s) => `Worse for every deck and overhead than: ${s}`,
    noStats: "This site has no chart-stats.json: the efficiency figures are not available.",
    axes: {
      displayLevel: "Level", density: "Density N/s", bpm: "Main BPM", bpmMax: "Max BPM", notes: "Notes",
      bgmMs: "BGM length (s)", perMinute: "Score/power/min", rate: "Score/power", base: "Base", skip: "Skip",
    },
    scatter: "Scatter", x: "X", y: "Y", levelDist: "Levels", bandShare: "Songs per band",
    moenotes: "Open in moenotes", moenotesHint: "Credits, vocals, audio, jacket and chart previews on the moenotes song page",
    detail: {
      musicType: "Song type", bgm: "BGM", musicId: "Music id", scoreId: "Chart id", notes: "Notes", fullCombo: "Full combo", density: "Density", bpm: "BPM",
      bpmChanges: (n) => `${n} changes`, span: "Notes span", musicLength: "Chart length", timeline: "Timeline",
      fever: "Fever", skill: "Skill", composition: "Notes by kind", weights: "Skill position weights",
      weightsHint: "Score per point of power that +100 % at a position adds. Put the strongest skill on the highest.",
      efficiency: "Efficiency (current settings)", close: "Close",
    },
    kinds: { tap: "Tap", flick: "Flick", slide: "Slide", trace: "Trace", combo: "Combo tick" },
    loading: "Loading…", error: "error", source: (r, v) => `Data: region ${r} · master ${v}`,
  },
};

// The guide: [section title, intro, [[term, meaning, why it matters], ...]] and the scenarios.
export const GUIDE = {
  zh: {
    title: "数据说明",
    intro: "这里解释页面上每个数字从哪里来、代表什么，以及不同玩法下应该重点看哪些。所有数据都直接读自游戏的 master 数据和谱面文件，"
      + "得分类数据由逐音符的精确得分模型推出并逐谱面核对。",
    sections: [
      ["谱面基础", "每张谱面固定不变的事实。", [
        ["等级", "谱面的显示等级（可带小数，如 26.5，比整数等级分得更细）。整数等级还参与得分：每个音符乘以等级系数 1 + (等级 − 5) × 0.5%。",
          "衡量难度的首要指标；同分数下等级高的谱面单音符分数略高。"],
        ["Notes", "需要判定的音符数，等于全连所需的连击数。不含隐藏音符和不判定的节点。",
          "音符越多，连击加成越早拉满，总分也越高；也是全连难度的粗略指标。"],
        ["音符构成", "点击、划键（Flick）、长条（起点 / 中继 / 终点）、追踪（Trace）和连击节点（长条上自动判定、只计连击）。",
          "划键和追踪多的谱面更考验手法；连击节点多的谱面音符数“虚高”，实际按键更少。"],
        ["BGM 时长", "音频本身的长度（读自音频文件的 cue 长度，未解码音频）。",
          "一局实际要花的时间主要由它决定。"],
        ["谱面长度", "最后一个音符 + 1 秒，是游戏得分代码使用的乐曲长度；技能效果最晚在这里结束。",
          "比 BGM 短（片尾没有音符）。想按“纯打歌时间”比较时选它。"],
        ["BPM", "主 BPM 是游玩区间（第一个到最后一个判定音符）里持续时间最长的 BPM；另有最高、最低 BPM 和变速次数。",
          "BPM 高、变速多的谱面节奏更难把握。"],
        ["密度 N/s", "判定音符数 ÷ 游玩区间的秒数。",
          "平均手速需求；看不出局部爆发段，但比 BPM 更直接反映忙不忙。"],
        ["Fever", "谱面里的 Fever 区间。", "决定得分节奏的段落。"],
        ["技能发动点", "谱面上固定的 5 个时刻。第 i 个时刻发动演出第 i 位成员的技能，效果持续 5 秒。",
          "发动点落在密集段的位置，技能收益就大，见“技能位权重”。"],
      ]],
      ["歌曲信息", "作词作曲、演唱、上线时间、音频、封面和 2D / 3D 谱面预览请点歌曲旁的 ↗ 去 moenotes 歌曲页查看，这里不重复。", [
        ["曲种", "master 数据的 musicType（1–5），卡牌的类型加成按它匹配。", "同一卡组在曲种匹配的歌上综合力更高，比较效率时要考虑。"],
      ]],
      ["得分与效率", "得分类数据都按“理论最佳打法”算：全 Perfect、全连、激走关闭，只计得分提升类技能。", [
        ["综合力 P", "卡组的综合力。在这个模型里得分和综合力成正比，所以页面上的数都是“每点综合力”的值，乘上你的综合力就是分数。", ""],
        ["基础系数", "不带任何技能时，得分 ÷ 综合力。例：基础系数 4.0、综合力 30 万 → 约 120 万分。",
          "反映谱面本身的“含分量”：音符多、等级高的谱面更高。"],
        ["技能位权重", "演出第 k 位的技能每 +100%，得分增加 综合力 × 权重。它等于该位置技能窗口（5 秒）里所有音符的得分系数之和。",
          "告诉你每个位置值多少：把最强的技能放在权重最高的位置。"],
        ["技能加成 %", "5 位成员技能的得分提升数值（例如满级 140%）。页面自动把最强的技能排到权重最高的位置（重排不等式保证这是最优）。",
          "填你自己卡组的数值，排行就是为你算的。"],
        ["分/综合力", "基础系数 + Σ 技能加成 × 技能位权重。一局的得分 = 综合力 × 它。", "单局能打多少分。"],
        ["每局额外耗时", "一局中打歌以外的时间：选曲、加载、结算、回到选曲。默认 30 秒，可拖动。",
          "额外耗时越大，长歌越划算；越小，短歌越划算。"],
        ["分/综合力/分钟", "分/综合力 ÷ ((时长 + 额外耗时) / 60)。", "单位时间能拿多少分，刷分效率的核心指标。"],
        ["相对", "当前列表里相对第一名的百分比。", ""],
        ["跳过系数", "使用跳过时，每点综合力的得分（全部按 Great、不计连击和技能）。", "用跳过券时看它，和时长无关。"],
        ["支配 / 前沿", "谱面 A 支配 B：无论技能数值多少、综合力多少、每局额外耗时多少，A 每分钟得分都不低于 B（且至少一种情况更高）。不被任何谱面支配的叫“前沿”。",
          "不管你的卡组和习惯如何，最优选择一定在前沿里；被支配的谱面可以放心不考虑。"],
        ["精度", "每个音符的得分取整最多损失 1 分，另有极小的浮点误差；每张谱面都用逐音符精确得分核对过误差上限。", ""],
      ]],
      ["局限", "", [
        ["同一综合力", "比较两首歌时假设卡组综合力相同。曲种和标签加成会让同一卡组在不同歌上的综合力不同，此时要在各自的综合力下比较。", ""],
        ["未计入", "激走（Gekisou）、Snap 技能、非 Perfect 判定、非得分类技能都不在这个模型里。", ""],
      ]],
    ],
    scenarioTitle: "不同场景看什么",
    scenarios: [
      ["活动刷分、按时间刷", "排行 › 效率", "填入自己卡组的技能数值，把每局额外耗时调到你实际的值，看“分/综合力/分钟”；勾“只看前沿”缩小范围。"],
      ["体力或次数有限，每局要最高分", "排行 › 效率（额外耗时拉满）或看“分/综合力”", "此时时长不重要，每局分数才重要；额外耗时拉到最大时排序就等于按单局得分排。"],
      ["用跳过券", "排行 › 跳过得分", "跳过不看时长也不看技能，直接比跳过系数。"],
      ["排卡", "谱面详情 › 技能位权重", "最强技能放权重最高的位置；各位置权重接近的谱面对排位不敏感。"],
      ["挑战高难", "排行 › 最高等级、最快", "等级是官方难度；密度和最高 BPM 反映手速，变速次数反映节奏难度。"],
      ["练习、入门", "图表 › 等级 × 密度", "从低等级、低密度、没有变速的谱面开始，逐步提高。"],
      ["冲全连", "谱面详情 › 音符构成", "Notes 多、划键和追踪多的谱面更难全连；连击节点多的谱面实际按键更少。"],
      ["整体挑歌", "图表 › 散点图", "任选两个指标（如 时长 × 效率、等级 × 密度）看全部谱面的分布，点点可看详情。"],
    ],
  },
  en: {
    title: "Guide",
    intro: "Where every figure on this page comes from, what it means, and which ones matter for what you are doing. "
      + "Everything is read from the game's master data and chart files; the score figures come from an exact per-note "
      + "score model, checked chart by chart.",
    sections: [
      ["Chart facts", "Fixed facts of each chart.", [
        ["Level", "The display level (with decimals such as 26.5, finer than the whole level). The whole level also scales every note's score by 1 + (level − 5) × 0.5 %.", "The official difficulty; higher levels score slightly more per note."],
        ["Notes", "Notes that are judged: the combo of a full combo. Hidden notes and unjudged ticks are left out.", "More notes fill the combo bonus sooner and score more; a rough full-combo difficulty."],
        ["Notes by kind", "Tap, flick, slide (begin / relay / end), trace, and combo ticks (judged on their own along a slide, combo only).", "Flicks and traces take technique; many combo ticks mean fewer actual inputs."],
        ["BGM length", "The length of the audio (the cue length of the audio file, not decoded).", "Mostly what a play costs in time."],
        ["Chart length", "The last note + 1 s: the music length of the game's score code; skill effects end there at the latest.", "Shorter than the BGM (no notes in the outro). Choose it to compare playing time only."],
        ["BPM", "Main BPM: the BPM that holds longest from the first to the last judged note; also the highest, the lowest and the number of changes.", "Fast and changing tempos are harder to read."],
        ["Density N/s", "Judged notes ÷ seconds from the first to the last judged note.", "The average speed a chart asks for (not its bursts)."],
        ["Fever", "The chart's fever ranges.", ""],
        ["Skill events", "Five fixed times; event i fires the skill of the member at performance position i, for 5 s.", "Events in dense parts are worth more: see the position weights."],
      ]],
      ["Song facts", "Credits, vocals, release, audio, jacket and 2D / 3D chart previews are on the moenotes song page (the ↗ next to a song); this page does not repeat them.", [
        ["Song type", "The master data's musicType (1–5), which card type bonuses match.", "The same deck has more power on songs of its type: keep it in mind when comparing efficiency."],
      ]],
      ["Score and efficiency", "All score figures are for the theoretical best play: all Perfect, full combo, Gekisou off, score-up skills only.", [
        ["Power P", "The deck's power. The score is proportional to it, so the page shows values per point of power: multiply by your power.", ""],
        ["Base", "Score ÷ power without skills. Base 4.0 at 300,000 power ≈ 1.2 million points.", "How much score the chart itself holds."],
        ["Position weights", "What +100 % of skill at performance position k adds, per point of power: the notes' score coefficients inside that skill's 5 s windows.", "What each position is worth: put the strongest skill on the highest."],
        ["Skill score up %", "The five members' score-up values (140 % at max). The page puts the strongest skill on the heaviest position, which is optimal.", "Enter your own deck's values."],
        ["Score/power", "Base + Σ skill value × position weight. One play scores power × this.", "What one play scores."],
        ["Overhead per play", "Time spent outside the song: choosing, loading, results. 30 s by default.", "More overhead favours long songs; less favours short ones."],
        ["Score/power/min", "Score/power ÷ ((length + overhead) / 60).", "Score per minute: the figure for grinding."],
        ["Rel.", "Percent of the list's first entry.", ""],
        ["Skip", "Score per point of power of a skipped live (all Great, no combo, no skills).", "What a skip ticket scores; the length does not matter."],
        ["Beaten / frontier", "A beats B when A scores at least as much per minute for every skill value, power and overhead (and more for some). Charts nothing beats form the frontier.", "Whatever your deck and habits, the best chart is on the frontier."],
        ["Accuracy", "Flooring loses at most one point per note, plus tiny float error; every chart is checked against the exact per-note score.", ""],
      ]],
      ["Limits", "", [
        ["Same power", "Comparisons assume the deck has the same power on both songs; song type and tag bonuses change it.", ""],
        ["Not modelled", "Gekisou, snap skills, non-Perfect judgements and skills that do not raise the score.", ""],
      ]],
    ],
    scenarioTitle: "What to look at",
    scenarios: [
      ["Grinding by time", "Rankings › Efficiency", "Enter your skill values and real overhead, compare score/power/min; tick Frontier only."],
      ["Limited plays, best score per play", "Rankings › Efficiency with the overhead at max, or Score/power", "Length stops mattering; the score of one play is what counts."],
      ["Skip tickets", "Rankings › Skip score", "Neither length nor skills count: compare the skip figure."],
      ["Building the deck order", "Chart detail › Position weights", "Strongest skill on the highest weight; charts with even weights do not care."],
      ["Hard charts", "Rankings › Highest level, Fastest", "Level is the official difficulty; density and max BPM show speed, BPM changes show rhythm."],
      ["Practice", "Charts › Level × density", "Start from low level, low density, no tempo changes."],
      ["Full combos", "Chart detail › Notes by kind", "Many notes, flicks and traces make it harder; combo ticks mean fewer inputs."],
      ["Choosing overall", "Charts › Scatter", "Plot any two figures (length × efficiency, level × density) and click a point for its detail."],
    ],
  },
};
