#!/usr/bin/env node
// The `ENGINE:` notes of src/: comments starting `// ENGINE:` mark behaviour that lives in Unity's or CRI's native
// code and is implemented from the engine's documented semantics. docs/fidelity.md lists them between the markers
// below; this script keeps that list in step with the sources.
//   node scripts/engine-notes.mjs            print the list (Markdown)
//   node scripts/engine-notes.mjs --write    replace the list in docs/fidelity.md
//   node scripts/engine-notes.mjs --check    exit 1 when docs/fidelity.md differs from the sources

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const DOC = path.join(root, "docs", "fidelity.md");
export const START = "<!-- engine-notes:start (generated by scripts/engine-notes.mjs) -->";
export const END = "<!-- engine-notes:end -->";

const files = (dir) => fs.readdirSync(dir, { withFileTypes: true }).flatMap((e) =>
  e.isDirectory() ? files(path.join(dir, e.name)) : e.name.endsWith(".js") ? [path.join(dir, e.name)] : []);

// [{file, notes: [text]}] in path order; a note is the rest of the line after `// ENGINE:`
export const collect = () => files(path.join(root, "src")).sort().map((f) => {
  const notes = [];
  for (const line of fs.readFileSync(f, "utf8").split("\n")) {
    const m = line.match(/\/\/\s*ENGINE:\s*(.*)$/);
    if (m && m[1] && !m[1].startsWith("`")) notes.push(m[1].trim());
  }
  return { file: path.relative(root, f).split(path.sep).join("/"), notes };
}).filter((x) => x.notes.length);

export const render = (groups) => {
  const out = [START, ""];
  for (const { file, notes } of groups) {
    out.push(`**\`${file}\`**`, "");
    for (const n of notes) out.push(`- ${n}`);
    out.push("");
  }
  out.push(END);
  return out.join("\n");
};

export const current = (doc) => {
  const a = doc.indexOf(START), b = doc.indexOf(END);
  if (a < 0 || b < a) throw new Error(`${path.relative(root, DOC)}: engine-notes markers not found`);
  return { before: doc.slice(0, a), list: doc.slice(a, b + END.length), after: doc.slice(b + END.length) };
};

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const list = render(collect());
  if (process.argv.includes("--write") || process.argv.includes("--check")) {
    const doc = fs.readFileSync(DOC, "utf8"), parts = current(doc);
    if (process.argv.includes("--check")) {
      if (parts.list !== list) { console.error("docs/fidelity.md: the ENGINE: list differs from src/ (run node scripts/engine-notes.mjs --write)"); process.exit(1); }
    } else fs.writeFileSync(DOC, parts.before + list + parts.after);
  } else console.log(list);
}
